# Generated by Django 6.0.2 on 2026-03-03 19:18

import ckeditor.fields
import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Site Management',
                'verbose_name_plural': 'Blog Site Management',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='core/company_logos/')),
                ('designation', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='I currently work here')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', help_text='Shown in the browser tab', max_length=100)),
                ('nav_name', models.CharField(default='Portfolio', help_text='The name shown in the navigation bar', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='The main logo of the site', upload_to='core/site/')),
                ('favicon', models.ImageField(blank=True, upload_to='core/site/')),
                ('hero_greeting', models.CharField(default='Hello, I am', max_length=100)),
                ('hero_name', models.CharField(default='Your Name', max_length=100)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_bg_image', models.ImageField(blank=True, help_text='Background image for hero section', upload_to='core/hero/')),
                ('hero_profile_image', models.ImageField(blank=True, help_text='Your transparent profile picture', upload_to='core/hero/')),
                ('resume_file', models.FileField(blank=True, help_text='Your CV/Resume', upload_to='core/docs/')),
                ('about_title', models.CharField(default='About Me', max_length=100)),
                ('about_description', models.TextField(blank=True)),
                ('about_who_am_i', models.TextField(blank=True, help_text="Text for the 'Who am I?' section")),
                ('contact_heading', models.CharField(default="Let's Connect!", max_length=100)),
                ('contact_sub_heading', models.CharField(blank=True, max_length=100)),
                ('contact_text', models.TextField(blank=True, help_text='Text shown below the sub-heading')),
                ('technical_skills_description', models.TextField(blank=True, help_text='Intro text for the Technical Skills section')),
                ('services_description', models.TextField(blank=True, help_text='Intro text for the My Services section')),
                ('projects_description', models.TextField(blank=True, help_text='Intro text for the Featured Projects section')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn Profile URL')),
                ('linkedin_logo', models.ImageField(blank=True, help_text='LinkedIn Logo (Transparent Background)', upload_to='core/social/')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook Profile URL')),
                ('facebook_logo', models.ImageField(blank=True, help_text='Facebook Logo (Transparent Background)', upload_to='core/social/')),
                ('github_url', models.URLField(blank=True, help_text='GitHub Profile URL')),
                ('github_logo', models.ImageField(blank=True, help_text='GitHub Logo (Transparent Background)', upload_to='core/social/')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram Profile URL')),
                ('instagram_logo', models.ImageField(blank=True, help_text='Instagram Logo (Transparent Background)', upload_to='core/social/')),
                ('x_url', models.URLField(blank=True, help_text='X (Twitter) Profile URL')),
                ('x_logo', models.ImageField(blank=True, help_text='X (Twitter) Logo (Transparent Background)', upload_to='core/social/')),
                ('footer_copyright', models.CharField(default='© 2026 All Rights Reserved.', max_length=200)),
                ('blog_section_title', models.CharField(default='My Blog', max_length=100)),
                ('blog_section_description', models.TextField(blank=True, help_text='About My Blog - shown under the My Blog container')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/pending/')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Cover Image', upload_to='core/projects/')),
                ('tech_stack', models.CharField(help_text='Comma separated technologies', max_length=200)),
                ('live_link', models.URLField(blank=True)),
                ('repo_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, help_text='Optional user picture', null=True, upload_to='core/reviews/')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Short comment about the service', max_length=70)),
                ('is_approved', models.BooleanField(default=True, help_text='Set to False to hide this review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fas fa-layer-group', help_text='Font Awesome class', max_length=50)),
                ('features', models.TextField(help_text='One feature per line')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
            ],
            options={
                'verbose_name': 'User Management',
                'verbose_name_plural': 'User Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='core/blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogViewTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browsing_source', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_tracks', to='core.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.homesettings'),
        ),
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='core/academic/')),
                ('degree_name', models.CharField(max_length=200)),
                ('institution_link', models.URLField(blank=True)),
                ('description', models.TextField(help_text='Bullet points separated by new lines')),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_backgrounds', to='core.homesettings')),
            ],
            options={
                'verbose_name_plural': 'Academic Background',
                'ordering': ['order', 'institution_name'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'About Me Main',
                'verbose_name_plural': 'About Me Main',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='ContactSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Menu',
                'verbose_name_plural': 'Contact Menu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Footer Text',
                'verbose_name_plural': 'Footer Text',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='HeroMainSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Main',
                'verbose_name_plural': 'Hero Main',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='HeroSocialSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='TechnicalSkillsSection',
            fields=[
            ],
            options={
                'verbose_name': 'Technical Skills',
                'verbose_name_plural': 'Technical Skills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu Name')),
                ('section_id', models.CharField(blank=True, help_text="HTML ID (auto-generated if empty). Use: 'home', 'about', 'experience', 'skills', 'projects', 'service', 'blog', 'contact' for existing sections.", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_menus', to='core.homesettings')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRAINING', 'Professional Training'), ('CERTIFICATION', 'Global Certification')], default='TRAINING', max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/training/')),
                ('certification_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_trainings', to='core.homesettings')),
            ],
            options={
                'verbose_name_plural': 'Professional Training & Certifications',
                'ordering': ['order', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCertificationModel',
            fields=[
            ],
            options={
                'verbose_name': 'Global Certification',
                'verbose_name_plural': 'Global Certifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
        migrations.CreateModel(
            name='ProfessionalTrainingModel',
            fields=[
            ],
            options={
                'verbose_name': 'Professional Training',
                'verbose_name_plural': 'Professional Trainings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='core/projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('date_to', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('time_from', models.TimeField(default=datetime.time(9, 0), verbose_name='Start Time')),
                ('time_to', models.TimeField(default=datetime.time(10, 0), verbose_name='End Time')),
                ('additional_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Booking',
                'verbose_name_plural': 'Service Bookings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Technology Name')),
                ('image', models.ImageField(upload_to='core/skills/', verbose_name='Image')),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('dominant_color', models.CharField(blank=True, default='', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.homesettings')),
            ],
            options={
                'verbose_name': 'Skill Card',
                'verbose_name_plural': 'Skill Cards',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='core.homesettings')),
            ],
            options={
                'verbose_name': 'Skill Category Label',
                'verbose_name_plural': 'Skill Category Labels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profiles/')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_field', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='core.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
