# Generated by Django 6.0.2 on 2026-03-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Set to False to hide this review'),
        ),
    ]
