# Generated by Django 6.0.2 on 2026-05-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_review_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Featured Projects',
                'verbose_name_plural': 'Featured Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='ServiceSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'My Services',
                'verbose_name_plural': 'My Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='core.homesettings'),
        ),
        migrations.AddField(
            model_name='service',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='core.homesettings'),
        ),
    ]
