# Generated by Django 6.0.2 on 2026-05-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectsectionsettings_servicesectionsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSectionSettings',
        ),
        migrations.DeleteModel(
            name='TechnicalSkillsSection',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Management', 'verbose_name_plural': 'Blog Management'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'My Service', 'verbose_name_plural': 'My Services'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Technical Skill', 'verbose_name_plural': 'Technical Skills'},
        ),
    ]
