# Generated by Django 6.0.2 on 2026-05-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_servicesectionsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSectionSettings',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Featured Project', 'verbose_name_plural': 'Featured Projects'},
        ),
    ]
