# Generated by Django 6.0.2 on 2026-05-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteviewertrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitorTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browsing_source', models.CharField(blank=True, max_length=500, null=True, verbose_name='Browsing Source')),
                ('path', models.CharField(max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='From')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='To')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Viewer Track',
                'verbose_name_plural': 'Site Viewer Tracking',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.DeleteModel(
            name='SiteViewerTrack',
        ),
    ]
